theme: jekyll-theme-cayman
domain: tuenvio.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://tuenvio.github.io  # the base hostname and protocol for your site, e.g. http://example.com
